version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore SmogBot.sln
build:
  verbosity: minimal
artifacts:
- path: BotFunctions
  name: AzureFunctions
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://smogbot.scm.azurewebsites.net:443/msdeploy.axd?site=SmogBot
  website: SmogBot
  username: $SmogBot
  password:
    secure: SN2RmUc0Y5X8UandjyfAOyRHlQhmzrPnkTbty0Gasj5lbH/7n3ZCfOjDX0f2mAjaqGyM/4D1bQT7vGYUJO3PWA==
  artifact: AzureFunctions
  do_not_use_checksum: true
  sync_retry_attempts: 5
- provider: SqlDatabase
  artifact: SmogBot.Database
  connection_string:
    secure: vGexDkzdzI52g2kdbnrpTEna88fTvcQYStuVvDANbv833Y3estWTZS1S04SmUbxm1GJHW2XuDXFjEQbQQqJ97OSp3tnF5bk+avMmiX/A3EV3yBVQ3f7fj2/7QnB4iodM1ySmKov5lWuEert3qaxCZ9IbAE54vvOzSgpWdq/wJkXnoyCXLAsvJ9U9UBSRZ9EPTlcXET2dfEH8CO2D2Q8n/Owx6WspKViUmOKgIxcO8806tzkDR+iK85EoQqVUrnWIrRy8QEV6jzoF7nXYBN/HOiv2u4PdAmRkOqU0yQZZGbaaShOsSupg2hq31+e1Qy6B
  register_data_tier_application: true
  script_database_options: true
  create_new_database: false
  block_on_possible_data_loss: true
  deploy_database_in_single_user_mode: false
  backup_database_before_changes: true
  drop_objects_not_in_source: true
  no_alter_statements_to_change_clr_types: false
  allow_drop_blocking_assemblies: false
  allow_incompatible_platform: true
  comment_out_set_var_declarations: false
  compare_using_target_collation: false
  disable_and_reenable_ddl_triggers: true
  do_not_alter_change_data_capture_objects: true
  do_not_alter_replicated_objects: true
  do_not_drop_users: true
  drop_constraints_not_in_source: true
  drop_dml_triggers_not_in_source: true
  drop_extended_properties_not_in_source: true
  drop_indexes_not_in_source: true
  drop_permissions_not_in_source: false
  drop_role_members_not_in_source: false
  generate_smart_defaults: false
  ignore_ansi_nulls: true
  ignore_authorizer: false
  ignore_column_collation: false
  ignore_comments: false
  ignore_cryptographic_provider_file_path: true
  ignore_ddl_trigger_order: false
  ignore_ddl_trigger_state: false
  ignore_default_schema: false
  ignore_dml_trigger_order: false
  ignore_dml_trigger_state: false
  ignore_extended_properties: false
  ignore_file_and_log_file_path: true
  ignore_filegroup_placement: true
  ignore_file_size: true
  ignore_fill_factor: true
  ignore_full_text_catalog_file_path: true
  ignore_identity_seed: false
  ignore_increment: false
  ignore_index_options: false
  ignore_index_padding: true
  ignore_keyword_casing: true
  ignore_lock_hints_on_indexes: false
  ignore_login_sids: true
  ignore_not_for_replication: false
  ignore_object_placement_on_partition_scheme: true
  ignore_partition_schemes: false
  ignore_permissions: false
  ignore_quoted_identifiers: true
  ignore_role_membership: false
  ignore_route_lifetime: true
  ignore_semicolon_between_statements: true
  ignore_table_options: false
  ignore_user_settings_objects: false
  ignore_whitespace: true
  ignore_with_nocheck_on_check_constraints: false
  ignore_with_nocheck_on_foreign_keys: false
  include_composite_objects: true
  include_transactional_scripts: false
  populate_files_on_file_groups: true
  script_database_collation: false
  script_database_compatibility: false
  script_deploy_state_checks: false
  script_file_size: false
  script_new_constraint_validation: true
  script_refresh_module: true
  treat_verification_errors_as_warnings: false
  unmodifiable_object_warnings: true
  verify_collation_compatibility: true
  verify_deployment: true
